volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: iisakov/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    entrypoint: /bin/sh -c "python manage.py migrate"

  frontend:
    env_file: .env
    image: iisakov/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: iisakov/kittygram_gateway
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend