#cloud-config
ssh_pwauth: no
users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "${SSH_KEY}"
write_files:
  - content: |
      #!/bin/bash

      # Опишите установку Docker
    path: "/root/vm_prep.sh"
    permissions: "0740"

runcmd:
  - sleep 120
  - sudo -i
  - /root/vm_prep.sh